#POST http://10.255.255.254:8080/users
POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "Novo Usuário",
    "email": "novo.usuario@gmail.com",
    "department": {
        "id": 1
    }
}